export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS";
export const GET_CHARACTER_DETAILS = "GET_CHARACTER_DETAILS";
export const CLEAN_CHARACTER_DETAILS = "CLEAN_CHARACTER_DETAILS";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const UPDATE_PAGE = "UPDATE_PAGE";